### ISSUE TITLE
Morph cards (except coin) don't cause transmutations

### ISSUE THREAD

**Issue by ballardrog** [RoganMurley/GALGAGAME#26]
From server/src/Cards.hs, it looks like morph wands transmute only morph wands into morph wands. (Instead of transmuting all morph cards to morph wands.) Similarly for grails and swords.

**Comment by RoganMurley** [comment]
Nice catch, thanks for flagging this.

**Comment by RoganMurley** [comment]
Just pushed a patch, should be live in ~30 mins.

https://github.com/RoganMurley/GALGAGAME/commit/23e57062589d1776063a47ce3ff24bfce8032a5f
