### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by zfrohardt** [RoganMurley/GALGAGAME#9]
Not sure if this is the correct place to leave this feedback, but I just played a game where the CPU played the card "Mimic" while the only other card in its hand was another "Mimic" card. This lead to an infinite loop of spawning "Mimic" cards. The card should probably be adjusted to prevent this behavior.

**Comment by RoganMurley** [comment]
As of today the "Mimic" card (now called"Empty Grail") no longer infinite loops as it can't copy a revealed card, and copying a card reveals it.
